### ISSUE TITLE
support metric format from dbt

### ISSUE THREAD

**Issue by danielefrigo** [metriql/metriql#42]
dbt is preparing a new feature called "metrics" for the upcoming 1.0 release:

https://next.docs.getdbt.com/docs/building-a-dbt-project/metrics
https://github.com/dbt-labs/dbt-core/issues/4071

Are you planning to support this metric definition format in metriql?

**Comment by danielefrigo** [comment]
Hi @buremba, sorry for the late answer.
This detail about dimensions definition let me really doubtful when I read it in dbt docs.
I agree with you, it's much more intuitive defining them at model level.

In order to leverage dbt metadata, an idea could be to expose at model level the intersection of the dimensions defined in the related metrics. It's more redundant to define, but could at least guarantee compatibility with the dbt metadata format (hoping they'll change their mind on this point in the future).

Makes sense?

**Comment by buremba** [comment]
@danielefrigo Actually, I had more time to dive into it for the last few days and found a way to integrate dbt's metric definitions to the downstream tools: We may expose these metrics as database tables rather than the measures. The `dimensions` definition picks the relevant columns from the target model and exposes them to the downstream tools in that case and the dataset can have a single metric definition.

We should still support our metric definitions under `models.meta` though and merge the dbt's metric definitions with our existing metric definitions approach for so that the dimension references can point to the dimension references under `models.meta` or `models.columns` for reusability and backward compatibility. 

That's similar to your idea and we will be able to support metrics as a first-class citizens.

**Comment by danielefrigo** [comment]
Maybe I misunderstood your explanation, but does this mean that using dbt metric definitions metriql will expose one separate dataset for each measure?
I understand where this comes from the dbt metric - dimension link, but on the other hand this could create great performance degredation and modeling complexities in BI tools since you often want to query multiple measures from the same fact table.

**Comment by buremba** [comment]
It's implemented in https://github.com/metriql/metriql/commit/0b133b7474b06f30aa836a7d4da8d9462a811e30! 🎉
