### ISSUE TITLE
Tableau Integration

### ISSUE THREAD

**Issue by emresemercioglu** [metriql/metriql#6]
We need to develop a Connector Plugin using the SDK:
https://tableau.github.io/connector-plugin-sdk/docs/
https://github.com/tableau/connector-plugin-sdk/tree/master/samples/scenarios/vendor_attributes/postgres_vendor
https://help.tableau.com/current/pro/desktop/en-us/examples_connector_sdk.htm

It should support basic auth and OAuth.

**Comment by buremba** [comment]
We decided to use Tableau's Presto data source as an interface because maintaining a connector plugin won't be reliable as we need to ship different plugins for different Tableau versions and install our driver explicitly. metriql simply acts as if it's a Presto cluster but returns virtual models as metadata and re-writes the MQL query as a segmentation query. See more info [here](https://metriql.com/integrations/jdbc-driver).

The only missing part is the metric definitions and the only way to integrate Tableau reliably is through the TDS files. We will generate the TDS files programmatically as a separate tool so that Tableau users click the TDS file and see their data models in an organizated way.

**Comment by akshay9319** [comment]
Hi All, Greetings of the day! I am trying to do a POC on on using metriql as a metric layer between Redshift and Tableau. Have followed the steps highlighted in the below link for the same. However, I am facing the attached error when trying to download the .tds file. Could someone please assist, on what could I be missing?

![](https://files.slack.com/files-pri/T023E7JM6QY-F043V8VFTC6/screenshot_2022-09-27_at_4.14.21_pm.png)

**Comment by buremba** [comment]
Hey @akshay9319 ! Sorry for the delay, we were out for the last week. Can you please send the metadata of the Metriql instance that you're running? It should be somewhere here: https://demo.metriql.com/api/v0/metadata

**Comment by akshay9319** [comment]
Hey @buremba, no worries! Shared the metadata over the Slack thread. Please check and advise.

**Comment by prince-lumiq** [comment]
Hii @buremba I am having aslo the exact error while downloading the TDS file.
My metadata file ithis:-
[metadata.zip](https://github.com/metriql/metriql/files/9731511/metadata.zip)
