### ISSUE TITLE
LOWER/UPPER

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#60]
When I'm trying to use LOWER in the where clause it still says "Not supported operation".
Using bigquery.

**Comment by buremba** [comment]
The UPPER/LOWER functions are supported in projection (i.e. `SELECT UPPER(dimension)`) but we don't support it inside the WHERE because if you need to filter the dimensions with `UPPER` function, you should define the dimension that encapsulates the UPPER function with the column/SQL definition. In case you want to run native SQL queries, you should use [SQL report type](https://metriql.com/query/sql) but MQL doesn't support this feature since it leverages the semantic model.

**Comment by buremba** [comment]
Feel free to open the issue if you think that the behavior is invalid or ambigious.
